name: Deploy Pages

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm install
      - run: npm run build
      - name: Upload artifact for pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./public
      - name: Deploy to GitHub pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages